version: '3.8'

services:
  food-order-system:
    build: .
    container_name: food-order-fulfillment
    volumes:
      - ./src:/app/src
    environment:
      - PYTHONPATH=/app/src
    command: python src/execution_harness.py
    stdin_open: true
    tty: true

  test-runner:
    build: .
    container_name: food-order-tests
    volumes:
      - ./src:/app/src
    environment:
      - PYTHONPATH=/app/src
    command: python src/test_kitchen.py
    depends_on:
      - food-order-system